name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: Boshen/setup-rust@92d71e4da65d4ae1f12e234c5bfa27b964ce994f # main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          components: clippy rustfmt
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings

  coverage:
    name: Run Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          cache-key: codecov
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-llvm-cov
          components: llvm-tools-preview

      - run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload to codecov.io
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: lcov.info

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: benchmark
          tools: cargo-codspeed

      - name: Build
        run: cargo codspeed build --bench bench_raytracing --features codspeed

      - uses: CodSpeedHQ/action@658a901452bb54c799643e060733b7afe9121b8d # v4.14.0
        timeout-minutes: 5
        with:
          mode: simulation
          run: cargo codspeed run
