name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: Boshen/setup-rust@053830d84d32d4e66b21382863df2ffd56a6fd83 # main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          components: clippy rustfmt
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: benchmark
          tools: cargo-codspeed

      - name: Build
        run: cargo codspeed build --bench bench_raytracing --features codspeed

      - uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        timeout-minutes: 5
        with:
          mode: simulation
          run: cargo codspeed run
