name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1
      - uses: Boshen/setup-rust@main
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          components: clippy rustfmt
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings

  coverage:
    name: Run Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: oxc-project/setup-rust@4f86b5d871ae7d24bc420e578be68964ab09e5cc # v1.0.15
        with:
          cache-key: codecov
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-llvm-cov
          components: llvm-tools-preview

      - run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload to codecov.io
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: lcov.info

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@83ed61bfbe2b8abbb3c66e8b65b1335484c70009 # v1.4.1

      - uses: oxc-project/setup-rust@4f86b5d871ae7d24bc420e578be68964ab09e5cc # v1.0.15
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: benchmark
          tools: cargo-codspeed

      - name: Build
        run: cargo codspeed build --bench bench_raytracing --features codspeed

      - uses: CodSpeedHQ/action@281164b0f014a4e7badd2c02cecad9b595b70537 # v4.11.1
        timeout-minutes: 5
        with:
          mode: simulation
          run: cargo codspeed run
