on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

name: CI

jobs:
  lints:
    name: Run cargo fmt and cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: Run cargo clippy
        run: cargo +nightly clippy -- -D warnings

      - name: Clean cache
        run: cargo install cargo-cache --no-default-features --features ci-autoclean && cargo-cache

  coverage:
    name: Run Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.19.0'
          args: '-- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: cobertura.xml

      - name: Clean cache
        run: cargo install cargo-cache --no-default-features --features ci-autoclean && cargo-cache
